name: Canary Release to Verdaccio

on:
  pull_request:
    paths:
      - .github/workflows/release-canary.yml
      - 'packages/**'
      - 'package.json'
      - 'lerna.json'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node (latest)
        uses: actions/setup-node@v1
        with:
          node_version: 13
      - name: Install
        run: yarn --frozen-lockfile
      - name: Clean
        run: yarn clean
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Publish
        run: |
          echo "//registry.verdaccio.org/:_authToken=${{ secrets.VERDACCIO_TOKEN }}" > .npmrc
          git update-index --assume-unchanged .npmrc
          yarn publish:canary
